version: '3.1'

services:
  phoenix:
    build:
      context: ..
      dockerfile: ./docker_dev/Dockerfile
    environment:
      SERVER_PORT: 4000
    ports:
      - "4000:4000"
      - "4443:4443"
    volumes:
      - ../:/app
